### ISSUE TITLE
how to use connon aimbot

### ISSUE THREAD

**Issue by fazanavard** [mitropolti/SEA-OF-THIEVES-CHEAT-PANEL#4]
how to use connon aimbot 
I used this cheat but I dont know where can I find how to use connon aimbot

**Comment by mitropolti** [comment]
There is only 'Cannon Predict'. Not 'Aimbot Cannon'.
As long as you have enabled 'Memory Write' option. 
Yellow or red cross will appear on your screen. (so you know where to shoot)
When you start shooting with cannons.
