### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by xFrone** [mitropolti/SEA-OF-THIEVES-CHEAT-PANEL#8]
It does not show enemy ships and artillery firing points. I think an update is needed

**Comment by mitropolti** [comment]
Update are avaliable since 04/03/2023! Thank you for star up!

**Comment by xFrone** [comment]
cannon aim helper not working, will there be an update about it?

**Comment by mitropolti** [comment]
Done, go check it out and ⭐up!
